### ISSUE TITLE
Failed Mendeley crawling published with partial data and wrong mapping

### ISSUE THREAD

**Issue by MortenHofft** [gbif/content-crawler#16]
The website suddenly showed 0 literature yesterday.

It turns out that the literature index only had 1500 records (unlike the normal ≈8K) and that the ES mapping had changed.

The problem was the same over many job (Daniel ran it several times).
Today it all runs fine again apparently.

It would be great if
a) it didn't swap index if the job fails.
b) that it marked the job as failed in Jenkins
c) that mappings was stable

Btw: Jenkins log files is around 650mb for each job

The only information that pops out to me in the log https://builds.gbif.org/job/run-content-crawler/6965/console is

```
INFO  [2019-07-25 11:52:15,255+0000] [main] org.gbif.content.crawl.mendeley.ElasticSearchIndexHandler: Indexed [500] documents
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: com.sun.jersey.api.client.UniformInterfaceException: HTTP 503: 
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:650)
	at org.gbif.content.crawl.mendeley.MendeleyDocumentCrawler.lambda$run$2(MendeleyDocumentCrawler.java:60)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:59)
	at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onNext(ObservableDoOnEach.java:103)
	at io.reactivex.internal.operators.observable.ObservableBuffer$BufferExactObserver.onComplete(ObservableBuffer.java:132)
	at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onComplete(ObservableDoOnEach.java:143)
	at io.reactivex.internal.operators.observable.ObservableFromIterable$FromIterableDisposable.run(ObservableFromIterable.java:112)
	at io.reactivex.internal.operators.observable.ObservableFromIterable.subscribeActual(ObservableFromIterable.java:57)
	at io.reactivex.Observable.subscribe(Observable.java:10151)
	at io.reactivex.internal.operators.observable.ObservableDoOnEach.subscribeActual(ObservableDoOnEach.java:42)
	at io.reactivex.Observable.subscribe(Observable.java:10151)
	at io.reactivex.internal.operators.observable.ObservableBuffer.subscribeActual(ObservableBuffer.java:44)
	at io.reactivex.Observable.subscribe(Observable.java:10151)
	at io.reactivex.internal.operators.observable.ObservableDoOnEach.subscribeActual(ObservableDoOnEach.java:42)
	at io.reactivex.Observable.subscribe(Observable.java:10151)
	at io.reactivex.Observable.subscribe(Observable.java:10137)
	at io.reactivex.Observable.subscribe(Observable.java:10043)
	at org.gbif.content.crawl.mendeley.MendeleyDocumentCrawler.run(MendeleyDocumentCrawler.java:58)
	at org.gbif.content.crawl.mendeley.MendeleyCrawlCommand.doRun(MendeleyCrawlCommand.java:37)
	at org.gbif.cli.BaseCommand.run(BaseCommand.java:136)
	at org.gbif.cli.Application.run(Application.java:97)
	at org.gbif.cli.Application.main(Application.java:146)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: com.sun.jersey.api.client.UniformInterfaceException: HTTP 503: 
	at org.gbif.content.crawl.mendeley.MendeleyDocumentCrawler.lambda$null$1(MendeleyDocumentCrawler.java:66)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.RuntimeException: com.sun.jersey.api.client.UniformInterfaceException: HTTP 503: 
	at org.gbif.content.crawl.mendeley.ComposeHandler.lambda$handleResponse$0(ComposeHandler.java:34)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:650)
	at org.gbif.content.crawl.mendeley.ComposeHandler.handleResponse(ComposeHandler.java:29)
	at org.gbif.content.crawl.mendeley.MendeleyDocumentCrawler.lambda$null$1(MendeleyDocumentCrawler.java:62)
	... 9 more
Caused by: com.sun.jersey.api.client.UniformInterfaceException: HTTP 503: 
	at org.gbif.ws.client.interceptor.HttpErrorResponseInterceptor.invoke(HttpErrorResponseInterceptor.java:59)
	at org.gbif.content.crawl.mendeley.ElasticSearchIndexHandler.lambda$null$3(ElasticSearchIndexHandler.java:188)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.gbif.content.crawl.mendeley.ElasticSearchIndexHandler.lambda$null$4(ElasticSearchIndexHandler.java:186)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.gbif.content.crawl.mendeley.ElasticSearchIndexHandler.lambda$null$5(ElasticSearchIndexHandler.java:186)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.gbif.content.crawl.mendeley.ElasticSearchIndexHandler.lambda$handleTags$11(ElasticSearchIndexHandler.java:183)
	at java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:899)
	at org.gbif.content.crawl.mendeley.ElasticSearchIndexHandler.handleTags(ElasticSearchIndexHandler.java:178)
	at org.gbif.content.crawl.mendeley.ElasticSearchIndexHandler.lambda$handleResponse$0(ElasticSearchIndexHandler.java:141)
	at java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:899)
	at org.gbif.content.crawl.mendeley.ElasticSearchIndexHandler.handleResponse(ElasticSearchIndexHandler.java:137)
	at org.gbif.content.crawl.mendeley.ComposeHandler.lambda$handleResponse$0(ComposeHandler.java:31)
	... 24 more
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: com.sun.jersey.api.client.UniformInterfaceException: HTTP 503: 
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:650)
	at org.gbif.content.crawl.mendeley.MendeleyDocumentCrawler.lambda$run$2(MendeleyDocumentCrawler.java:60)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:59)
	at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onNext(ObservableDoOnEach.java:103)
	at io.reactivex.internal.operators.observable.ObservableBuffer$BufferExactObserver.onComplete(ObservableBuffer.java:132)
	at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onComplete(ObservableDoOnEach.java:143)
	at io.reactivex.internal.operators.observable.ObservableFromIterable$FromIterableDisposable.run(ObservableFromIterable.java:112)
	at io.reactivex.internal.operators.observable.ObservableFromIterable.subscribeActual(ObservableFromIterable.java:57)
	at io.reactivex.Observable.subscribe(Observable.java:10151)
	at io.reactivex.internal.operators.observable.ObservableDoOnEach.subscribeActual(ObservableDoOnEach.java:42)
	at io.reactivex.Observable.subscribe(Observable.java:10151)
	at io.reactivex.internal.operators.observable.ObservableBuffer.subscribeActual(ObservableBuffer.java:44)
	at io.reactivex.Observable.subscribe(Observable.java:10151)
	at io.reactivex.internal.operators.observable.ObservableDoOnEach.subscribeActual(ObservableDoOnEach.java:42)
	at io.reactivex.Observable.subscribe(Observable.java:10151)
	at io.reactivex.Observable.subscribe(Observable.java:10137)
	at io.reactivex.Observable.subscribe(Observable.java:10043)
	at org.gbif.content.crawl.mendeley.MendeleyDocumentCrawler.run(MendeleyDocumentCrawler.java:58)
	at org.gbif.content.crawl.mendeley.MendeleyCrawlCommand.doRun(MendeleyCrawlCommand.java:37)
	at org.gbif.cli.BaseCommand.run(BaseCommand.java:136)
	at org.gbif.cli.Application.run(Application.java:97)
	at org.gbif.cli.Application.main(Application.java:146)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: com.sun.jersey.api.client.UniformInterfaceException: HTTP 503: 
	at org.gbif.content.crawl.mendeley.MendeleyDocumentCrawler.lambda$null$1(MendeleyDocumentCrawler.java:66)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.RuntimeException: com.sun.jersey.api.client.UniformInterfaceException: HTTP 503: 
	at org.gbif.content.crawl.mendeley.ComposeHandler.lambda$handleResponse$0(ComposeHandler.java:34)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:650)
	at org.gbif.content.crawl.mendeley.ComposeHandler.handleResponse(ComposeHandler.java:29)
	at org.gbif.content.crawl.mendeley.MendeleyDocumentCrawler.lambda$null$1(MendeleyDocumentCrawler.java:62)
	... 9 more
Caused by: com.sun.jersey.api.client.UniformInterfaceException: HTTP 503: 
	at org.gbif.ws.client.interceptor.HttpErrorResponseInterceptor.invoke(HttpErrorResponseInterceptor.java:59)
	at org.gbif.content.crawl.mendeley.ElasticSearchIndexHandler.lambda$null$3(ElasticSearchIndexHandler.java:188)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.gbif.content.crawl.mendeley.ElasticSearchIndexHandler.lambda$null$4(ElasticSearchIndexHandler.java:186)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.gbif.content.crawl.mendeley.ElasticSearchIndexHandler.lambda$null$5(ElasticSearchIndexHandler.java:186)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.gbif.content.crawl.mendeley.ElasticSearchIndexHandler.lambda$handleTags$11(ElasticSearchIndexHandler.java:183)
	at java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:899)
	at org.gbif.content.crawl.mendeley.ElasticSearchIndexHandler.handleTags(ElasticSearchIndexHandler.java:178)
	at org.gbif.content.crawl.mendeley.ElasticSearchIndexHandler.lambda$handleResponse$0(ElasticSearchIndexHandler.java:141)
	at java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:899)
	at org.gbif.content.crawl.mendeley.ElasticSearchIndexHandler.handleResponse(ElasticSearchIndexHandler.java:137)
	at org.gbif.content.crawl.mendeley.ComposeHandler.lambda$handleResponse$0(ComposeHandler.java:31)
	... 24 more
```

**Comment by dnoesgaard** [comment]
fwiw, running the crawler on dev works fine, e.g. 

https://builds.gbif.org/job/run-content-crawler/7222/

**Comment by timrobertson100** [comment]
I have a suspicion that we put an index live on error cases by using `doOnTerminate()` instead of `onCompeted()` [here](https://github.com/gbif/content-crawler/blob/master/src/main/java/org/gbif/content/crawl/mendeley/MendeleyDocumentCrawler.java#L65)

I'll try and create a test case for this

**Comment by timrobertson100** [comment]
While I believe that commit is an improvement, this still indexes records into ES as we go and I'm not yet confident this won't swap in an ES index to go live on failure scenarios.
